name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt || true
          pip install -r docs/requirements-dev.txt || true

      # 4. Build HTML docs
      - name: Build HTML
        working-directory: ./docs
        run: |
          make clean
          make html

      # 5. Deploy to docs/pages/ folder on main branch
      - name: Deploy to docs/pages/ folder
        run: |
          # Create docs/pages folder if it doesn't exist
          mkdir -p ./docs/pages
          
          # Copy built HTML files to docs/pages folder
          cp -r ./docs/pages/html/* ./docs/pages/
          
          # Configure git
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Add and commit changes
          git add ./docs/pages/
          git commit -m "Update Sphinx documentation" || echo "No changes"
          git push origin main
    