name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt || true
          pip install -r docs/requirements-dev.txt || true

      # 4. Build HTML docs
      - name: Build HTML
        working-directory: ./docs
        run: |
          make clean
          make html

      # 5. Copy built files to temporary location (before cleaning)
      - name: Copy built files
        run: |
          mkdir -p ./temp_docs
          cp -r ./docs/pages/html/* ./temp_docs/

      # 6. Clean build directory
      - name: Clean build directory
        working-directory: ./docs
        run: |
          make clean

      # 7. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_docs
          publish_branch: gh-pages
          keep_files: true
    